Use bash instead of sh and update logging on lock
Signed-off-by: Tor Krill <tor@openproducts.se>

diff --git a/kgp-update b/kgp-update
--- a/kgp-update
+++ b/kgp-update
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/bash
 
 #
 # Upgrade is performed as follows
@@ -20,13 +20,6 @@
 
 # Find home
 
-# Make sure update not already in progress
-LOCKFILE="/var/run/lock/kgp-updates.lock"
-
-# Get fd to backup lock file
-exec {lock_fd}>"${LOCKFILE}"
-flock -n "$lock_fd" || { report "Unable to start upgrade, upgrade already running."; exit 0 ;}
-
 
 CURDIR=`realpath $0`
 SB=`dirname $CURDIR`
@@ -38,6 +31,13 @@ echo "SB: $SB"
 . $SB/utils.sh
 
 log_debug "Path: ${SB} "
+
+# Make sure update not already in progress
+LOCKFILE="/var/run/lock/kgp-updates.lock"
+
+# Get fd to backup lock file
+exec {lock_fd}>"${LOCKFILE}"
+flock -n "$lock_fd" || { log_warn "Unable to start upgrade, upgrade already running"; exit 0 ;}
 
 #
 # Execute all executables in $1 dir
